# Generated by Django 3.0.4 on 2020-05-15 16:27

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_vsvideos_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsvideos',
            name='Meta_Title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vsvideos',
            name='Meta_keyword',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vsvideos',
            name='Video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=videos.models.user_directory_path_thumbnail),
        ),
    ]
