# Generated by Django 3.0.6 on 2020-05-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200514_2354'),
        ('categorys_and_reatings', '0001_initial'),
        ('videos', '0003_auto_20200515_0927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VsReating',
            new_name='VsRating',
        ),
        migrations.AlterModelOptions(
            name='vsrating',
            options={'verbose_name_plural': 'VS Rating'},
        ),
    ]
