# Generated by Django 3.0.6 on 2020-05-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20200520_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsvideos',
            name='Views',
            field=models.IntegerField(default=0),
        ),
    ]
