# Generated by Django 3.0.6 on 2020-05-30 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_vsvideos_reating'),
    ]

    operations = [
        migrations.CreateModel(
            name='VsNonRegisterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=500, null=True)),
                ('watch_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('User_ip', models.CharField(blank=True, max_length=500, null=True)),
                ('Video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VsVideos_VsNonRegisterUser', to='videos.VsVideos')),
            ],
            options={
                'verbose_name_plural': 'VS Non Register User',
            },
        ),
    ]
