# Generated by Django 3.0.6 on 2020-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_vsnonregisteruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsvideos',
            name='mail_send_status',
            field=models.BooleanField(default=False),
        ),
    ]
