# Generated by Django 3.0.6 on 2020-06-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_vsvideos_mail_send_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsvideos',
            name='Videos_Slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
