# Generated by Django 3.0.4 on 2020-05-14 15:02

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsusers',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=account.models.user_directory_path_favicon),
        ),
        migrations.AlterField(
            model_name='vsusers',
            name='name',
            field=models.CharField(default='User', max_length=20),
        ),
    ]
