# Generated by Django 3.0.4 on 2020-05-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_vsusers_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsusers',
            name='user_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
