# Generated by Django 3.0.4 on 2020-05-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_vsusers_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsusers',
            name='otp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
