# Generated by Django 3.0.6 on 2020-06-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200514_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsusers',
            name='Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
