# Generated by Django 3.0.6 on 2020-06-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200611_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsusers',
            name='Contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
