# Generated by Django 3.0.6 on 2020-06-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200615_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsusers',
            name='password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
