# Generated by Django 3.0.4 on 2020-05-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vssystemsettings',
            old_name='No_of_videos_watch_after_ogin',
            new_name='No_of_videos_watch_after_login',
        ),
    ]
