# Generated by Django 3.0.4 on 2020-05-20 06:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_auto_20200514_2354'),
        ('videos', '0003_auto_20200515_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='VsFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_VsFavourite', to='account.VsUsers')),
                ('Video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VsVideos_VsFavourite', to='videos.VsVideos')),
            ],
        ),
    ]
