# Generated by Django 3.0.4 on 2020-05-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourite_videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vsfavourite',
            options={'verbose_name_plural': 'VS Favourite'},
        ),
    ]
