# Generated by Django 3.0.4 on 2020-05-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourite_videos', '0002_auto_20200519_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vsfavourite',
            old_name='User',
            new_name='VsUser',
        ),
    ]
