# Generated by Django 3.0.6 on 2020-06-02 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200514_2354'),
        ('favourite_videos', '0003_auto_20200520_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vsfavourite',
            name='Video',
        ),
        migrations.AddField(
            model_name='vsfavourite',
            name='Subscribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VsUsers_VsFavourite', to='account.VsUsers'),
        ),
    ]
