# Generated by Django 3.0.6 on 2020-06-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20200605_0713'),
        ('favourite_videos', '0005_vssendemailfornewvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsfavourite',
            name='Video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VideoFavourite', to='videos.VsVideos'),
        ),
    ]
