# Generated by Django 3.0.6 on 2020-05-27 13:06

from django.db import migrations, models
import manage_cms_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VsCmsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500, unique=True)),
                ('keywork', models.CharField(max_length=500, unique=True)),
                ('Background_Image', models.ImageField(blank=True, null=True, upload_to=manage_cms_page.models.user_directory_path_backgrount_image)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Page_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
