# Generated by Django 3.0.6 on 2020-05-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_cms_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vscmspage',
            options={'verbose_name_plural': 'VS CMS Page Content'},
        ),
    ]
