# Generated by Django 3.0.7 on 2020-07-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_cms_page', '0002_auto_20200527_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='vscmspage',
            name='set_order',
            field=models.IntegerField(default=0),
        ),
    ]
