# Generated by Django 3.0.6 on 2020-05-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vshomepagesettings',
            name='Facebook_Page_Link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vshomepagesettings',
            name='Instagram_Page_Link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vshomepagesettings',
            name='LinkedIn_Page_Link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vshomepagesettings',
            name='Twitter_Page_Link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
