# Generated by Django 3.0.7 on 2020-07-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200530_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='vshomepagesettings',
            name='Session_3_box_1_Counter_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vshomepagesettings',
            name='Session_3_box_2_Counter_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vshomepagesettings',
            name='Session_3_box_3_Counter_start',
            field=models.IntegerField(default=0),
        ),
    ]
