# Generated by Django 3.0.6 on 2020-05-30 08:14

import categorys_and_reatings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys_and_reatings', '0002_vsreatingattribute_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vsreatingattribute',
            name='Image',
        ),
        migrations.AddField(
            model_name='vscategory',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=categorys_and_reatings.models.user_directory_path_category_image),
        ),
    ]
